# Site settings
title: mm-partner
safe:           false
source:         app
exclude:
  - assets/scripts
  - assets/vendor
  - assets/styles
  - README.md
timezone: America/New_York
highlighter: false

domain:         https://www.missingmaps.org
path_prefix:    /partners

default_partner: all
gems:
  - jekyll-redirect-from

collections:
  partner:
    output: true
    permalink: /:path/
    lang: en
